### ISSUE TITLE
DATA4PTToolsv0.4.2 everyLineIsReferenced

### ISSUE THREAD

**Issue by marasonic** [ITxPT/DATA4PTTools#49]
const journeyLinePath = xpath.join(
  xpath.path.FRAMES,
  "TimetableFrame",
  "vehicleJourneys",
  "ServiceJourney",
);

In the EPIP-based documents, the LineRef cannot be specified within ServiceJourney. Instead, the Line is referenced from the: 
  ServiceJourneyPattern id="C::ServiceJourneyPattern:1::" version="any"
    RouteView id="C::RouteView:1::"
      LineRef ref="C::Line:1::"
or
  routes
    Route id="C::Route:1: version="any"
      LineRef ref="C::Line:1"

**Comment by pkvarnfors** [comment]
This validation script is not intended for use with the EPIP profile. We are currently modifying the tool so that it will be clearer which scripts that works for a selected profile. We will also add a concept of packages which includes both a XSD and the scripts for validating a given profile. So if you select the EPIP package you will get the correct XSD and also the corresponding scripts.
