### ISSUE TITLE
xsd validation is too slow

### ISSUE THREAD

**Issue by skinkie** [ITxPT/DATA4PTTools#9]

**Comment by thbar** [comment]
I can give a specific example with data file. I have tried to validate a largish file (~222MB unzipped) which can be found at https://transport.data.gouv.fr/datasets/horaires-des-lignes-ter-sncf/?locale=en, section "NeTEx resources". Heads-up: the file is entitled "Export au format CSV" but this is a data import bug that we must fix. Also, the file contains (at time of writing) a single encoding error (ISO-8859-1 instead of UTF-8, see https://github.com/etalab/transport-qualite-des-donnees/issues/4) which you will have to fix manually for now.

I have started running the validator outside of Docker, directly on a recent Mac M1, and the process has been running for 40 minutes, and it isn't finished.

Happy to provide more input if needed!

**Comment by pkvarnfors** [comment]
We are aware of the performance issues but have so far prioritized to get the tool and web interface to a working state, including some extra validation scripts and better documentation. We will look more into how we can improve the performance in coming releases.

**Comment by pkvarnfors** [comment]
It is very useful to get examples of working and not working/slow files, thank you for that.

**Comment by pkvarnfors** [comment]
Fixed in version 0.5.5
